# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d5e0fe5666c7fa7383dc080fca988567"
name = "alwin-astral-dev"
application_url = "https://holmes-gamma-mounted-wave.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "itzmealwii.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://holmes-gamma-mounted-wave.trycloudflare.com/auth/callback",
  "https://holmes-gamma-mounted-wave.trycloudflare.com/auth/shopify/callback",
  "https://holmes-gamma-mounted-wave.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
